# Generated by Django 2.2.4 on 2019-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.CharField(max_length=100)),
                ('FirstName', models.CharField(default='fuck', max_length=100)),
                ('LastName', models.CharField(default=' you', max_length=100)),
            ],
        ),
    ]
