# Generated by Django 2.2.4 on 2019-08-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorsite', '0002_auto_20190825_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postuserscore',
            options={'ordering': ('-Score',)},
        ),
    ]
