# Generated by Django 2.2.4 on 2019-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorsite', '0003_auto_20190825_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='xxxxxxxx', max_length=100)),
                ('CharHead', models.CharField(default=0, max_length=100)),
                ('CharBody', models.CharField(default=0, max_length=100)),
                ('Tutorial', models.CharField(default=0, max_length=100)),
                ('CooksScore', models.CharField(default=0, max_length=100)),
                ('CooksQuiz', models.CharField(default=0, max_length=100)),
                ('HomesScore', models.CharField(default=0, max_length=100)),
                ('HomesQuiz', models.CharField(default=0, max_length=100)),
                ('ToysScore', models.CharField(default=0, max_length=100)),
                ('ToysQuiz', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
